trigger:
  branches:
    include:
    - main
    - develop

variables:
- name: agentName
  value: 'ubuntu-latest'
- name: nodeVersion
  value: '14.18.0'

pool:
  vmImage: $(agentName)

steps:
- task: NodeTool@0
  displayName: Use Node $(nodeVersion)
  inputs:
    versionSpec: $(nodeVersion)

- script: |
    npm install
  displayName: 'Install Dependencies'

- script: |
    sed -i -e "s/\(\"version\":\\s\+\"\([0-9]\+\.\?\)\+\)/\1-pre.$BUILD_BUILDNUMBER/" package.json;
  displayName: 'Setup Preview Version'
  condition: and(succeeded(), ne(variables['Build.SourceBranch'], 'refs/heads/main'))

- script: |
    npm run build
    npm run test
  displayName: 'Build and Test Source'

- task: Npm@1
  inputs:
    command: custom
    customCommand: publish --tag next
    customEndpoint: 'npm_registry'
  displayName: 'Publish Pre-Package'
  condition: and(succeeded(), ne(variables['Build.SourceBranch'], 'refs/heads/main'))

- task: Npm@1
  inputs:
    command: publish
    publishEndpoint: 'npm_registry'
  displayName: 'Publish Package'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
