trigger:
  branches:
    include:
    - master
    - develop

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node'

- script: |
    npm install
  displayName: 'Install Dependencies'

- script: |
    sed -i -e "s/\(\"version\":\\s\+\"\([0-9]\+\.\?\)\+\)/\1-pre.$BUILD_BUILDNUMBER/" package.json;
  displayName: 'Setup Preview Version'
  condition: and(succeeded(), ne(variables['Build.SourceBranch'], 'refs/heads/master'))

- script: |
    npm run build
  displayName: 'Build Source'

- script: |
    npm pack
  displayName: 'Compile Package'

- task: Npm@1
  inputs:
    command: publish
    publishEndpoint: 'npm_registry'
  displayName: 'Publish Package'
  condition: and(succeeded(), in(variables['Build.SourceBranch'], 'refs/heads/master', 'refs/heads/develop'))
